### [ 7TogkKeyShop ] ###

# use § To Change Colors Text

# Need plugin EconomyAPI and PiggyCrate to launch this plugin

Title: " §l§b»§r§7 [§bKeyShops§7]"
1:
  Key:
    Name: "Check" # Key Name
    Price: 100000 # Price key
  Button:
    Name: "Check Key" # Button Name
  Message:
    Succes: "§aSucces buy a key Check" # Success Message Buy A Key
    Failed: "§cYour money is not enough" # Failed Message Buy A Key
2:
  Key:
    Name: "Glory"
    Price: 500000
  Button:
    Name: "Glory Key"
  Message:
    Succes: "§aSucces buy a key Glory"
    Failed: "§cYour money is not enough"
